---
- name: Create a new user with sudo privileges
  hosts: your_server_hostname
  become: yes

  vars:
    new_username: newuser
    new_user_password: "{{ vaulted_new_user_password }}"

  tasks:
    - name: Create new user account
      become: yes
      user:
        name: "{{ new_username }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/bash
        home: "/home/{{ new_username }}"

    - name: Create home directory for new user
      become: yes
      file:
        path: "/home/{{ new_username }}"
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: '0755'

    - name: Add new user to sudoers
      become: yes
      lineinfile:
        dest: "/etc/sudoers"
        regexp: '^%sudo\s'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'

    - name: Reload sudoers
      become: yes
      command: 'sudo --validate'
