---
- name: Update and upgrade packages
  hosts: test ktnhat02.minagro.local
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Check for upgradable packages
      command: apt list --upgradable
      register: upgradable_packages
      changed_when: false

    - name: Perform upgrade if there are upgradable packages
      apt:
        upgrade: safe
      when: "'upgradable' in upgradable_packages.stdout"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Show hosts that need a restart
      debug:
        msg: "Host {{ inventory_hostname }} needs a restart."
      when: reboot_required.stat.exists
